name: build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: lts/gallium
    - run: yarn install --prefer-offline
    - run: yarn run build
    - uses: actions/upload-artifact@v3
      with:
        path: dist/
